#!/bin/bash

echo "📱 === Configuración ADB WiFi para Debug Real ==="
echo ""
echo "🔧 PASOS PARA USAR TU CELULAR:"
echo ""
echo "1️⃣ En tu celular Android:"
echo "   - Ve a Configuración > Acerca del teléfono"
echo "   - Toca 7 veces en 'Número de compilación'"
echo "   - Ve a Configuración > Opciones de desarrollador"
echo "   - Activa 'Depuración USB'"
echo "   - Activa 'Depuración inalámbrica' (Android 11+)"
echo ""
echo "2️⃣ Conecta por USB primero:"
echo "   - Conecta tu celular por USB"
echo "   - Ejecuta: adb devices"
echo "   - Acepta la autorización en el celular"
echo ""
echo "3️⃣ Cambiar a WiFi:"
echo "   - Ejecuta: adb tcpip 5555"
echo "   - Desconecta USB"
echo "   - Busca la IP de tu celular (Configuración > WiFi)"
echo "   - Ejecuta: adb connect [IP_DEL_CELULAR]:5555"
echo ""
echo "4️⃣ Instalar y debuggear:"
echo "   - adb install DroneScanMinimal.apk"
echo "   - adb logcat | grep DroneScan"
echo ""
echo "✅ VENTAJAS:"
echo "   - No ocupa espacio en Codespace"
echo "   - Performance real"
echo "   - Testing en hardware real"
echo "   - Más rápido que emulador"
echo ""
echo "📋 Para compilar la APK:"
echo "   cd DroneScanMinimal && ./gradlew assembleDebug"
